### PR TITLE
New column 'QUANTIFIER' to make USER_CODE unique in IDN_OAUTH2_DEVICE_FLOW

### PR DESCRIPTION
**Pull request by SupunSPWithana**
**Related PR**: https://github.com/wso2-extensions/identity-inbound-auth-oauth/pull/1569

**Related to**: https://github.com/wso2/product-is/issues/7348

**Purpose**
Adding new column 'QUANTIFIER' to make USER_CODE unique in Device Authorization Grant (Device Flow).

**Product Version**
Wso2 IS 5.10.0

### CODE REVIEW

**Comment by madurangasiriwardena** [comment]
Please add the modification to the DDL queries, rather than alterations since these are used to create the databases new.

**Review by madurangasiriwardena — APPROVED** [review]

**Review by ashensw — APPROVED** [review]

**Comment by janakamarasena** [comment]
We need to have migration support for this. Please point to the relevant migration issue and the PR as well.

**Comment by somindatommy** [comment]
@janakamarasena @ashensw can we get this PR merged?

**Comment by somindatommy** [comment]
@SupunSPWithana shall we point to the relevant migration issue?
>@SupunSPWithana We need to have migration support for this. Please point to the relevant migration issue and the PR as well.

**Review by janakamarasena — APPROVED** [review]

**Comment by janakamarasena** [comment]
Related migration PR https://github.com/wso2-extensions/identity-migration-resources/pull/196

**Pull request merged**
