### PR TITLE
Add new inbuilt conditional function end authentication as failure

### PR DESCRIPTION
**Pull request by Akila94**
## Purpose

The purpose of this PR is to implement a new inbuilt conditional function to end the authentication as a failure without redirecting to an error page.

Issue: https://github.com/wso2/carbon-identity-framework/issues/2975

Tested with the current master version and verified.

## Documentation

The documentation of the newly introduced function should be written. The doc issue is submitted [here](https://github.com/wso2/docs-is/issues/1821).

### CODE REVIEW

**Comment by janakamarasena** [comment]
Hi @Akila94, with regards to documentation please add the details requested here [1]. 

[1] - https://github.com/wso2/docs-is/issues/1821#issuecomment-649225292

**Comment by senthalan** [comment]
Fix https://github.com/wso2/carbon-identity-framework/pull/2981

**Comment by Akila94** [comment]
@janakamarasena , I've updated the things you've asked in wso2/docs-is#1821

**Comment by Akila94** [comment]
Updated the PR with unit tests. Please review and merge.

**Pull request merged**
